config/routes.rb
ChallengeCoffeeme::Application.routes.draw do
  resources :users
  resources :drinks
  resources :orders

  root 'orders#index'
end

app/models/drink.rb
class Drink < ActiveRecord::Base
  validates_presence_of :name

  LARGE = "Large"
  REGULAR = "Regular"
  SMALL = "Small"

  SIZE = [LARGE, REGULAR, SMALL]
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user,  inverse_of: :orders
  belongs_to :drink, inverse_of: :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders, inverse_of: :user

  validates_presence_of :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
	end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController 
  def index
  	@drinks = Drink.all
  end

  def new
  	@drink = Drink.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
  	@orders = Order.all
  	respond_with(@orders)
  end

  def new
  	@order = Order.new
  end

  def create
  	@order = Order.new order_params
  	respond_to do |format|
	  if @order.save
	  	format.html { redirect_to @order, notice: 'Order was successfully created.' }
	  	format.json { render json: @order, status: :created, location: @order }
	  else
	  	format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
  	  end
  	end
  end

  def update
  	respond_to do |format|
  	  if @order.update_attributes order_params
  	  	format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
  	end
  end

  def destroy
  	@order.destroy
  	respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def show
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit( :name, :comment, :user_id, :drink_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h4>Orders List</h4>

app/views/drinks/index.html.erb
<div id="drinks"></div>

<script type="text/javascript" charset="utf-8">
  jQuery(function(){
  	new App({el: $('#drinks')});
  });
</script>

app/views/layouts/_navigation.html.erb
<%= link_to 'CoffeeMe', root_path, class: 'brand' %>
<ul class="nav">
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Drinks', drinks_path %></li>
  <li><%= link_to 'Orders', orders_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>CoffeeMe</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
      <div class="container-fluid">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/orders/index.html.erb
<div id="orders"></div>

<script type="text/javascript" charset="utf-8">
  jQuery(function(){
  	new App({el: $('#orders')});
  });
</script>

app/views/users/index.html.erb
<div id="users"></div>

<script type="text/javascript" charset="utf-8">
  jQuery(function(){
  	new App({el: $('#users')});
  });
</script>